"""add stage status history

Revision ID: 06b91c8d1f47
Revises: 907f0d27abba
Create Date: 2025-07-29 13:44:25.807626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06b91c8d1f47"
down_revision: Union[str, None] = "907f0d27abba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stage_status_history",
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stage_status_history")
    # ### end Alembic commands ###
