"""upd subpr_tmp 2

Revision ID: 325bea76457e
Revises: e6fef1cf84c4
Create Date: 2025-07-23 14:05:03.170435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325bea76457e'
down_revision: Union[str, None] = 'e6fef1cf84c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stage_templates_subproject_template_id_key'), 'stage_templates', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('stage_templates_subproject_template_id_key'), 'stage_templates', ['subproject_template_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
