"""add cascade

Revision ID: 864eac073847
Revises: 10bc574a62b6
Create Date: 2025-07-12 21:48:18.775329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "864eac073847"
down_revision: Union[str, None] = "10bc574a62b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("messages_stage_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "stages", ["stage_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("stages_subproject_id_fkey"), "stages", type_="foreignkey")
    op.create_foreign_key(None, "stages", "subprojects", ["subproject_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("subprojects_project_id_fkey"), "subprojects", type_="foreignkey")
    op.create_foreign_key(None, "subprojects", "projects", ["project_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subprojects", type_="foreignkey")
    op.create_foreign_key(op.f("subprojects_project_id_fkey"), "subprojects", "projects", ["project_id"], ["id"])
    op.drop_constraint(None, "stages", type_="foreignkey")
    op.create_foreign_key(op.f("stages_subproject_id_fkey"), "stages", "subprojects", ["subproject_id"], ["id"])
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(op.f("messages_stage_id_fkey"), "messages", "stages", ["stage_id"], ["id"])
    # ### end Alembic commands ###
