"""add create-update fields

Revision ID: baf6a5b6b049
Revises: e8262aa42cdb
Create Date: 2025-07-18 01:52:22.577240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baf6a5b6b049'
down_revision: Union[str, None] = 'e8262aa42cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
