"""upd subpr_tmp 3

Revision ID: d2598ea0dee1
Revises: 325bea76457e
Create Date: 2025-07-23 15:20:30.721173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2598ea0dee1"
down_revision: Union[str, None] = "325bea76457e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("subproject_templates_project_id_key"), "subproject_templates", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("subproject_templates_project_id_key"),
        "subproject_templates",
        ["project_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
