"""upd descriptions

Revision ID: d6123eca6dff
Revises: 7708818e40b9
Create Date: 2025-07-13 04:32:25.836425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6123eca6dff"
down_revision: Union[str, None] = "7708818e40b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "description", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("stages", "description", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("subprojects", "description", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subprojects", "description", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("stages", "description", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("projects", "description", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
