"""upd subpr_tmp

Revision ID: e6fef1cf84c4
Revises: 38a8186f8cd8
Create Date: 2025-07-23 05:54:52.386904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6fef1cf84c4"
down_revision: Union[str, None] = "38a8186f8cd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subproject_templates", "description")
    op.drop_column("subproject_templates", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subproject_templates", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.add_column(
        "subproject_templates", sa.Column("description", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
